apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-example-java-dynamic-point-of-sale-display
spec:
  info:
    title: Large data sharing Golang web app
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-example-java-dynamic-point-of-sale.git
      sourceType: git
  ui:
    input:
      variables:
        labels:
          name: labels
          title: Labels
        project_id:
          name: project_id
          title: Project Id
        region:
          name: region
          title: Region
        resource_name_suffix:
          name: resource_name_suffix
          title: Resource Name Suffix
